# Generated by Django 6.0.5 on 2026-05-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='time',
        ),
    ]
